exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("features")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("features").insert([
        {
          id: 1,
          user_id: 1,
          project_id: 1,
          title: "Knex",
          done: false,
          keyInfo: "key information here",
          tools: "tools",
          description: "description1",
          notes: "notes1",
          structure: "",
          start: new Date(2020, 12, 1),
          end: new Date(2020, 12, 2),
        },
        {
          id: 2,
          user_id: 1,
          project_id: 1,
          title: "Knex",
          done: false,
          keyInfo: "key information here",
          tools: "tools",
          description: "description1",
          notes: "notes1",
          structure: "",
          start: new Date(2020, 12, 1),
          end: new Date(2020, 12, 2),
        },
        {
          id: 3,
          user_id: 1,
          project_id: 1,
          title: "Knex",
          done: false,
          keyInfo: "key information here",
          tools: "tools",
          description: "description1",
          notes: "notes1",
          structure: "",
          start: new Date(2020, 12, 1),
          end: new Date(2020, 12, 2),
        },
        {
          id: 4,
          user_id: 2,
          project_id: 2,
          title: "Play",
          done: false,
          keyInfo: "key information here",
          tools: "tools",
          description: "description1",
          notes: "notes1",
          structure: "",
          start: new Date(2020, 12, 1),
          end: new Date(2020, 12, 2),
        },
        {
          id: 5,
          user_id: 2,
          project_id: 2,
          title: "Talk",
          done: false,
          keyInfo: "key information here",
          tools: "tools",
          description: "description1",
          notes: "notes1",
          structure: "",
          start: new Date(2020, 12, 1),
          end: new Date(2020, 12, 2),
        },
        {
          id: 6,
          user_id: 2,
          project_id: 2,
          title: "Hang",
          done: false,
          keyInfo: "key information here",
          tools: "tools",
          description: "description1",
          notes: "notes1",
          structure: "",
          start: new Date(2020, 12, 1),
          end: new Date(2020, 12, 2),
        },
        {
          id: 7,
          user_id: 3,
          project_id: 3,
          title: "Laugh",
          done: false,
          keyInfo: "key information here",
          tools: "tools",
          description: "description1",
          notes: "notes1",
          structure: "",
          start: new Date(2020, 12, 1),
          end: new Date(2020, 12, 2),
        },
        {
          id: 8,
          user_id: 3,
          project_id: 3,
          title: "Love",
          done: false,
          keyInfo: "key information here",
          tools: "tools",
          description: "description1",
          notes: "notes1",
          structure: "",
          start: new Date(2020, 12, 1),
          end: new Date(2020, 12, 2),
        },
        {
          id: 9,
          user_id: 3,
          project_id: 3,
          title: "Marry",
          done: false,
          keyInfo: "key information here",
          tools: "tools",
          description: "description1",
          notes: "notes1",
          structure: "",
          start: new Date(2020, 12, 1),
          end: new Date(2020, 12, 2),
        },
      ]);
    });
};
